apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: org
    app: teamkatalog-bigquery-naisjob
  name: teamkatalog-bigquery-naisjob
  namespace: org
spec:
  image: {{ image }}
  ttlSecondsAfterFinished: 340
  backoffLimit: 2
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
#  schedule: '50 5,11,17,23 * * *'
  schedule: '*/15 * * * *'
  webproxy: true
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/run/secrets/nais.io/vault/GOOGLE_APPLICATION_CREDENTIALS
  vault:
    enabled: true
