name: Build and deploy

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    name: build and push docker container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push docker image
        env:
          GH_USER: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GH_TOKEN} | docker login ghcr.io --username ${GH_USER} --password-stdin
          docker build -t ${IMAGE} .
          docker push ${IMAGE}
      - name: Deploy prod
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: .nais/naisjob.yaml,.nais/alert.yaml
