name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and push docker container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: org
          salsa: false
      - name: Deploy prod
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-fss
          RESOURCE: .nais/naisjob.yaml,.nais/alert.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-build-push.outputs.telemetry }}
